### ISSUE TITLE
Epic Issues

### ISSUE THREAD

**Issue by NCC-Lykos** [NCC-Lykos/neocron-classic#1]
This is to notate and help fix Epics

- [x] City Admin
- [x] Diamond Real Estate
- [x] NEXT
- [x] Tangent Technologies
- [x] Biotech
- [x] Proto Pharma
- [x] Tsunami
- [x] Black Dragon
- [x] The Crahn Sect
- [x] The City Mercs
- [x] The Fallen Angels
- [x] Twilight Guardian

The check marked factions have working Epics.

**Comment by NCC-Lykos** [comment]
This was fixed as the temporary HQ for TG was added in Canyon.
