### ISSUE TITLE
Trader Checklist

### ISSUE THREAD

**Issue by Skansy** [NCC-Lykos/neocron-classic#6]
To have an Overview about Traders in Major Citys and add missing or repair broken ones.
Full  TraderList: https://docs.google.com/spreadsheets/d/1CkhgRQ8-oYQMCIJmRbvLy_qOv8T0bK30TDYvzIANKXU

### Weapons
- [x] Low Tech Melee Weapons `Military Base 1 - Retail Area 1 (A&W)`
- [x] High Tech Melee Weapons `Military Base 1 - Retail Area 1 (A&W)`
- [x] Low Tech Pistols `Military Base 1 - Retail Area 1 (A&W)`
- [x] High Tech Pistols
- [x] Low Tech Rifles `Military Base 1 - Retail Area 1 (A&W)`
- [x] High Tech Rifles `Military Base 1 - Retail Area 1 (HEW)`
- [x] Low Tech Cannons `Military Base 1 - Retail Area 1 (A&W)`
- [x] High Tech Cannons `Military Base 1 - Retail Area 1 (HEW)`
- [x] Drones
### Ammo
- [x] Low Tech Pistol Ammo `Military Base 1 - Retail Area 1 (A&W)`
- [x] High Tech Pistol Ammo `Military Base 1 - Retail Area 1 (HEW)`
- [x] Low Tech Rifle Ammo `Military Base 1 - Retail Area 1 (A&W)`
- [x] High Tech Rifle Ammo `Military Base 1 - Retail Area 1 (HEW)`
- [x] Low Tech Cannon Ammo `Military Base 1 - Retail Area 1 (A&W)`
- [x] High Tech Cannon Ammo `Military Base 1 - Retail Area 1 (HEW)`
### Armor
- [x] Basic Armor `Military Base 1 - Retail Area 1 (A&W)`
- [x] Advanced Armor
- [x] Power Armor (Tank + PE) `Military Base 1 - Next to the Genrep`
### Psi Stuff
- [x] PSI (Armor & Implants) `Military Base 1 - First Crossing from GR`
- [x] PSI APU Moduls `Military Base 1 - First Crossing from GR`
- [x] PSI PPU Moduls `Military Base 1 - First Crossing from GR`
### Vehicles + Turret
- [x] Vehicle Keys `Military Base 1 - Retail Area 1 (ASG)`
- [x] Vehicle Ammo
- [x] Turrets 
### Tradeskills
- [x] Tools `Military Base 1 - Retail Area 2 (Crytons)`
- [x] Chemicals `Military Base 1 - Retail Area 2 (Crytons)`
- [x] Item Parts `Military Base 1 - Retail Area 2 (Crytons)`
- [x] Lube & Stuff
- [x] Implants `Military Base 1 - Retail Area 2 (Crytons)`
- [x] Bones `Military Base 1 - Retail Area 2 (Crytons)`
### Food / Meds / Drugs
- [x] Medis / Drugs `Military Base 1 - Retail Area 2 (Tylors)`
- [x] LoM Pills `Military Base 1 - Retail Area 2 (Tylors)`
- [x] Food `Military Base 1 - Retail Area 2 (Restaurant)`
### All Buyer
- [x] All Buyer `Military Base 1 - Retail Area 2 (Tylors)`
### Apartment
- [x] Apartment Keys
- [x] Apartment Furniture `Military Base 1 - Runnerhousing (YO's) // Only Crap Furniture from YOs`

### Weapons
- [x] Low Tech Melee Weapons  `Tech Haven Sec-1 - Archer & Wesson`
- [x] High Tech Melee Weapons `Tech Haven Sec-1 - Archer & Wesson`
- [x] Low Tech Pistols `Tech Haven Sec-1 - Archer & Wesson`
- [x] High Tech Pistols `Tech Haven Sec-2 - lower circle`
- [x] Low Tech Rifles `Tech Haven Sec-1 - Archer & Wesson`
- [x] High Tech Rifles `Tech Haven Sec-2 - lower circle`
- [x] Low Tech Cannons `Tech Haven Sec-1 - Archer & Wesson`
- [x] High Tech Cannons
- [x] Drones
### Ammo
- [x] Low Tech Pistol Ammo `Tech Haven Sec-1 - Archer & Wesson`
- [x] High Tech Pistol Ammo `Tech Haven Sec-2 - lower circle`
- [x] Low Tech Rifle Ammo `Tech Haven Sec-1 - Archer & Wesson`
- [x] High Tech Rifle Ammo `Tech Haven Sec-2 - lower circle`
- [x] Low Tech Cannon Ammo `Tech Haven Sec-1 - Archer & Wesson`
- [x] High Tech Cannon Ammo `Tech Haven Sec-2 - lower circle`
### Armor
- [x] Basic Armor `Tech Haven Sec-2 - lower circle`
- [x] Advanced Armor
- [x] Power Armor (Spy) `Tech Haven Sec-2 - upper circle`
- [x] Heavy Belts `Tech Haven Sec-2 - upper circle`
### Psi Stuff
- [x] PSI (Armor & Implants) `Tech Haven Sec-3 - Trader Area`
- [x] PSI APU Moduls `Tech Haven Sec-3 - Trader Area`
- [x] PSI PPU Moduls `Tech Haven Sec-3 - Trader Area`
### Vehicles + Turret
- [x] Vehicle Keys `Tech Haven Sec-3 - Trader Area`
- [x] Vehicle Ammo
- [x] Turrets
### Tradeskills
- [x] Tools `Tech Haven Sec-2 - inner circle`
- [x] Chemicals `Tech Haven Sec-2 - inner circle`
- [x] Item Parts `Tech Haven Sec-3 - Trader Area`
- [x] Lube & Stuff `Tech Haven Sec-2 - inner circle`
- [x] Implants `Tech Haven Sec-3 - Trader Area`
- [x] Bones `Tech Haven Sec-3 - Trader Area`
### Food / Meds / Drugs
- [x] Medis / Drugs `Tech Haven Sec-2 - inner circle`
- [x] LoM Pills `Tech Haven Sec-2 - inner circle`
- [x] Food `Tech Haven Sec-1 - Below Runnerhousing`
### All Buyer
- [x] All Buyer `Tech Haven Sec-1 - Archer & Wesson // Sales Assistant (Fallen Angels)`
### Apartment
- [x] Apartment Keys
- [x] Apartment Furniture 

### Weapons
- [x] Low Tech Melee Weapons `Canyon - Fist Weaponry`
- [x] High Tech Melee Weapons `Canyon - Fist Weaponry`
- [x] Low Tech Pistols `Canyon - Fist Weaponry`
- [x] High Tech Pistols
- [x] Low Tech Rifles `Canyon - Fist Weaponry`
- [x] High Tech Rifles `Canyon - Fist Weaponry`
- [x] Low Tech Cannons
- [x] High Tech Cannons
- [x] Drones
### Ammo
- [x] Low Tech Pistol Ammo `Canyon - Fist Weaponry`
- [x] High Tech Pistol Ammo `Canyon - Fist Weaponry`
- [x] Low Tech Rifle Ammo `Canyon - Fist Weaponry`
- [x] High Tech Rifle Ammo `Canyon - Fist Weaponry`
- [x] Low Tech Cannon Ammo `Canyon - Fist Weaponry`
- [x] High Tech Cannon Ammo `Canyon - Fist Weaponry`
### Armor
- [x] Basic Armor `Canyon - Fist Weaponry`
- [x] Advanced Armor `Canyon - Fist Weaponry`
- [x] Power Armor (Camo Tank + PE) `Canyon - Fist Weaponry`
### Psi Stuff
- [x] PSI (Armor & Implants)
- [x] PSI APU Moduls
- [x] PSI PPU Moduls
### Vehicles + Turret
- [ ] Vehicle Keys
- [x] Vehicle Ammo `Canyon - Fist Weaponry`
- [x] Turrets `Canyon - Fist Weaponry`
### Tradeskills
- [x] Tools
- [x] Chemicals
- [x] Item Parts
- [x] Lube & Stuff
- [x] Implants
- [x] Bones
### Food / Meds / Drugs
- [x] Medis / Drugs
- [x] LoM Pills
- [x] Food `Canyon - Above Genrep`
### All Buyer
- [x] All Buyer
### Apartment
- [x] Apartment Keys
- [x] Apartment Furniture 

### Weapons
- [x] Low Tech Melee Weapons  `Plaza Sec-3 - (A&W)`
- [x] High Tech Melee Weapons `Plaza Sec-2 - (A&W)`
- [x] Low Tech Pistols `Plaza Sec-1 - (A&W)`
- [x] High Tech Pistols `Plaza Sec-2 - (HEW)`
- [x] Low Tech Rifles `Plaza Sec-4 - (A&W)`
- [x] High Tech Rifles `Plaza Sec-2 - (HEW)`
- [x] Low Tech Cannons `Plaza Sec-3 - (A&W)`
- [x] High Tech Cannons `Plaza Sec-3 - (HEW)`
- [x] Drones
### Ammo
- [x] Low Tech Pistol Ammo `Plaza Sec-1 - (A&W)`
- [x] High Tech Pistol Ammo `Plaza Sec-2 - (HEW)`
- [x] Low Tech Rifle Ammo `Plaza Sec-4 - (A&W)`
- [x] High Tech Rifle Ammo `Plaza Sec-2 - (HEW)`
- [x] Low Tech Cannon Ammo `Plaza Sec-3 - (A&W)`
- [x] High Tech Cannon Ammo `Plaza Sec-3 - (HEW)`
### Armor
- [x] Basic Armor `Plaza Sec-2 - (A&W)`
- [x] Advanced Armor
- [x] Power Armor (Monk) `Plaza Sec-1 - (Yakarma - Skywalk)`
### Psi Stuff
- [x] PSI (Armor & Implants) `Plaza Sec-1 - (Yakarma)`
- [x] PSI APU Moduls `Plaza Sec-1 - (Yakarma)`
- [x] PSI PPU Moduls `Plaza Sec-1 - (Yakarma)`
### Vehicles + Turret
- [x] Vehicle Keys `Plaza Sec-3 - (ASG)`
- [x] Vehicle Ammo
- [x] Turrets
### Tradeskills
- [x] Tools `Plaza Sec-1 - (Crytons)`
- [x] Chemicals `Plaza Sec-1 - (Crytons)`
- [x] Item Parts `Plaza Sec-1 - (Crytons)`
- [x] Lube & Stuff `Plaza Sec-1 - (Crytons)`
- [x] Implants `Plaza Sec-1 - (Crytons)`
- [x] Bones `Plaza Sec-1 - (Crytons)`
### Food / Meds / Drugs
- [x] Medis / Drugs `Plaza Sec-1 - (Medicare)`
- [x] LoM Pills
- [x] Food `Plaza Sec-1 - (Garriots)`
### All Buyer
- [x] All Buyer `Plaza Sec-1 - (YO's)`
### Apartment
- [x] Apartment Keys `Plaza Sec-1 - (Diamond)`
- [x] Apartment Furniture

**Comment by NCC-Lykos** [comment]
I'm going to close this as @ncc-gnisha has put a lot of work in. If you could open a new one after the patch that would be great.
